= EntityModule

EntityModule provides the developer with infrastructure for building user interfaces to manage the entities of an application.
Combined with xref:admin-web-module::index.adoc[AdminWebModule] it attempts to automatically generate a UI based on entity metadata.

== How it works
At the heart is the `EntityRegistry`, which contains a map of all available entities in the application.
An entity is backed by an `EntityConfiguration`, which is a full meta model of what makes up the entity and possibly how it can be identified, fetched and persisted.
Based on the available entity model, default administration screens in xref:admin-web-module::index.adoc[Admin Web] can be generated.
These can also be fully customized and extended using configuration classes and custom components.

== Spring Data support
EntityModule has built-in support for Spring Data repositories.
All Spring Data repositories in an application will be detected and registered.
A CRUD UI for those entities will be available with sorting and searching capabilities where possible.

== Dependency
The EntityModule dependency is present in xref:across:releases:platform/release-notes.adoc[Across Platform].

[source,xml]
----
<dependency>
    <groupId>com.foreach.across.modules</groupId>
    <artifactId>entity-module</artifactId>
</dependency>
----

== Getting started
A good introduction can be found in the xref:quick-start.adoc[quick start].
