= 4.x.x release notes

[#4-0-0]
== 4.0.0-SNAPSHOT

* Behaviour of `EntityLinkBuilder` has been changed due to changes in Spring 5 concerning URL encoding of parameters.
** All `linkTo` calls in `EntityViewLinks` will automatically URL encode `from` parameters correctly.
** All calls to `withPartial`, `withFromUrl`, `withViewName`, `withQueryParam` will automatically URL encode `from` parameters correctly.
** Calls to to `.queryParam` are now seen as literals and will not be url encoded anymore.
If you want query parameters to be encoded you must use templated variables as seen on https://docs.spring.io/spring/docs/5.1.12.RELEASE/spring-framework-reference/web.html#web-uri-encoding.
* fix bug with `EntityIdProxyPropertyRegistrar`: when an id value is `null` the `EntityModel.findOne()` of the target entity will no longer be called
* the default navigation items generated for Across module are now by default included in the breadcrumb.
Register `Menu` attribute `AdminMenu.ATTR_BREADCRUMB` to exclude them again, see also the xref:admin-web-module:building/nav-sections#exclude-from-breadcrumb[AdminWebModule documentation]
* the generic *Entity management* overview controller is no longer available
