= 4.x.x release notes

[#4-1-0]
== 4.1.0.RELEASE

* Changed `new PageRequest()` to `PageRequest.of()`
* Changed `new Sort()` to `Sort.by()`
* Removed hardcoded dependency to hibernate-jpa-2.1-api which was restricting us to work with JPA 2.2
* Pinned version of cypress because of incompatibility between `cypress/browsers:chrome65-ff57` and `node8`
* Switched to JUnit5

[#4-0-0]
== 4.0.0.RELEASE

* *Requires Across 5.0.0.*
* Behaviour of `EntityLinkBuilder` has been changed due to changes in Spring 5 concerning URL encoding of parameters.
** All `linkTo` calls in `EntityViewLinks` will automatically URL encode `from` parameters correctly.
** All calls to `withPartial`, `withFromUrl`, `withViewName`, `withQueryParam` will automatically URL encode `from` parameters correctly.
** Calls to to `.queryParam` are now seen as literals and will not be url encoded anymore.
If you want query parameters to be encoded you must use templated variables as seen on https://docs.spring.io/spring/docs/5.0.8.BUILD-SNAPSHOT/spring-framework-reference/web.html#web-uri-encoding.
