[[detail-view]]
= Detail view

The detail view enables a user to view an existing instance for an entity type, without being able to modify the entity directly.
It can only be accessed if the user has the `AllowableAction.READ` action.
The detail view is the default entry point to view an instance and provides the following:

links to associated entities::
By default, tabs are generated for properties that are `ManyToOne` / `OneToMany` and `ManyToMany` relationships.
link to the deleteView for the instance::
Usually visualized as a garbage-bin icon at the top right of the navigation bar.
link to the updateView for the instance::
A *modify* button is provided when the user has the `AllowableAction` action.
links to other registered views/urls::
By intercepting the `EntityAdminMenuEvent` additional menu items can be configured which will be accessible via the navigation bar.

// TODO refer to documentation on customizing the entity admin menu

.Configuring a detail view
[source,java,indent=0]
----
public void configure(EntitiesConfigurer entities)
{
    entities.withType( Book.class )
            .detailView(
                fvb -> fvb.showProperties( ".", "~publication" ) # <1>
            );
}
----
<1> Show the previously selected properties but exclude publication.

.Default settings
[cols="1,1", opts="header"]
|===

| View name
| view

| Required action
| `AllowableAction.READ`

| ViewElementMode
| `ViewElementMode.FORM_READ`

| Default property selector
| `EntityPropertyDescriptor.READABLE`

|===

== Related documentation

* To learn more about configuring a form view, please see xref::building-views/customizing-views/form-view.adoc[CRUD views]
